development:
  adapter: postgresql
  encoding: unicode
  database: taxi2_development
  host: localhost
  pool: 5432
  username: thomasgalibert
  password: totolasito

test:
  adapter: postgresql
  encoding: unicode
  database: taxi2_test
  host: localhost
  pool: 5432
  username: thomasgalibert
  password: totolasito

production:
  adapter: postgresql
  encoding: unicode
  database: taxi2_production
  host: localhost
  pool: 5432
  username: thomasgalibert
  password: totolasito
